export default [
  { value: 'AL', title: 'AL - Alabama'},
  { value: 'AK', title: 'AK - Alaska'},
  { value: 'AS', title: 'AS - American Samoa'},
  { value: 'AZ', title: 'AZ - Arizona'},
  { value: 'AR', title: 'AR - Arkansas'},
  { value: 'CA', title: 'CA - California'},
  { value: 'CO', title: 'CO - Colorado'},
  { value: 'CT', title: 'CT - Connecticut'},
  { value: 'DE', title: 'DE - Delaware'},
  { value: 'DC', title: 'DC - District of Columbia'},
  { value: 'FM', title: 'FM - Federated Stated of Micronesia'},
  { value: 'FL', title: 'FL - Florida'},
  { value: 'GA', title: 'GA - Georgia'},
  { value: 'GU', title: 'GU - Guam'},
  { value: 'HI', title: 'HI - Hawaii'},
  { value: 'ID', title: 'ID - Idaho'},
  { value: 'IL', title: 'IL - Illinois'},
  { value: 'IN', title: 'IN - Indiana'},
  { value: 'IA', title: 'IA - Iowa'},
  { value: 'KS', title: 'KS - Kansas'},
  { value: 'KY', title: 'KY - Kentucky'},
  { value: 'LA', title: 'LA - Louisiana'},
  { value: 'ME', title: 'ME - Maine'},
  { value: 'MH', title: 'MH - Marshall Islands'},
  { value: 'MD', title: 'MD - Maryland'},
  { value: 'MA', title: 'MA - Massachusetts'},
  { value: 'MI', title: 'MI - Michigan'},
  { value: 'MN', title: 'MN - Minnesota'},
  { value: 'MS', title: 'MS - Mississippi'},
  { value: 'MO', title: 'MO - Missouri'},
  { value: 'MT', title: 'MT - Montana'},
  { value: 'NE', title: 'NE - Nebraska'},
  { value: 'NV', title: 'NV - Nevada'},
  { value: 'NH', title: 'NH - New Hampshire'},
  { value: 'NJ', title: 'NJ - New Jersey'},
  { value: 'NM', title: 'NM - New Mexico'},
  { value: 'NY', title: 'NY - New York'},
  { value: 'NC', title: 'NC - North Carolina'},
  { value: 'ND', title: 'ND - North Dakota'},
  { value: 'MP', title: 'MP - Northern Mariana Islands'},
  { value: 'OH', title: 'OH - Ohio'},
  { value: 'OK', title: 'OK - Oklahoma'},
  { value: 'OR', title: 'OR - Oregon'},
  { value: 'PW', title: 'PW - Palau'},
  { value: 'PA', title: 'PA - Pennsylvania'},
  { value: 'PR', title: 'PR - Puerto Rico'},
  { value: 'RI', title: 'RI - Rhode Island'},
  { value: 'SC', title: 'SC - South Carolina'},
  { value: 'SD', title: 'SD - South Dakota'},
  { value: 'TN', title: 'TN - Tennessee'},
  { value: 'TX', title: 'TX - Texas'},
  { value: 'UT', title: 'UT - Utah'},
  { value: 'VT', title: 'VT - Vermont'},
  { value: 'VI', title: 'VI - Virgin Islands'},
  { value: 'VA', title: 'VA - Virginia'},
  { value: 'WA', title: 'WA - Washington'},
  { value: 'WV', title: 'WV - West Virginia'},
  { value: 'WI', title: 'WI - Wisconsin'},
  { value: 'WY', title: 'WY - Wyoming'},
  { value: 'AA', title: 'AA - Armed Forces Americas'},
  { value: 'AE', title: 'AE - Armed Forces Africa'},
  { value: 'AE', title: 'AE - Armed Forces Canada'},
  { value: 'AE', title: 'AE - Armed Forces Europe'},
  { value: 'AE', title: 'AE - Armed Forces Middle East'},
  { value: 'AP', title: 'AP - Armed Forces Pacific'}
];
